# Generated by Django 4.2.4 on 2023-09-05 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="data",
            new_name="date",
        ),
    ]
